/**
 * services/notification-service.ts
 * Real backend API calls for notifications.
 */

import type { Notification } from '@/types'
import { getToken } from '@/lib/auth'

const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000/api'

function authHeaders(): HeadersInit {
  const token = getToken()
  return {
    'Content-Type': 'application/json',
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  }
}

async function handleResponse<T>(res: Response): Promise<T> {
  const json = await res.json()
  if (!res.ok) throw new Error(json.message || `Request failed: ${res.status}`)
  return json
}

// ── GET /api/notifications ────────────────────────────────────
export async function getNotifications(_userId?: string): Promise<Notification[]> {
  const res = await fetch(`${API_BASE}/notifications`, { headers: authHeaders() })
  const json = await handleResponse<{ success: boolean; data: Notification[]; unreadCount: number }>(res)
  return json.data
}

export async function getUnreadCount(): Promise<number> {
  const res = await fetch(`${API_BASE}/notifications?limit=1`, { headers: authHeaders() })
  const json = await handleResponse<{ unreadCount: number }>(res)
  return json.unreadCount
}

// ── PUT /api/notifications/:id/read ──────────────────────────
export async function markAsRead(id: string): Promise<void> {
  const res = await fetch(`${API_BASE}/notifications/${id}/read`, {
    method: 'PUT',
    headers: authHeaders(),
  })
  await handleResponse<{ success: boolean }>(res)
}

// ── PUT /api/notifications/read-all ──────────────────────────
export async function markAllAsRead(_userId?: string): Promise<void> {
  const res = await fetch(`${API_BASE}/notifications/read-all`, {
    method: 'PUT',
    headers: authHeaders(),
  })
  await handleResponse<{ success: boolean }>(res)
}

// ── DELETE /api/notifications/:id ────────────────────────────
export async function deleteNotification(id: string): Promise<void> {
  const res = await fetch(`${API_BASE}/notifications/${id}`, {
    method: 'DELETE',
    headers: authHeaders(),
  })
  await handleResponse<{ success: boolean }>(res)
}

// ── DELETE /api/notifications/clear-all ──────────────────────
export async function clearAllNotifications(): Promise<void> {
  const res = await fetch(`${API_BASE}/notifications/clear-all`, {
    method: 'DELETE',
    headers: authHeaders(),
  })
  await handleResponse<{ success: boolean }>(res)
}

// Legacy compat — no-op (notifications are auto-generated by backend)
export async function addNotification(): Promise<void> {}
